### ISSUE TITLE
Data and image tasks

### ISSUE THREAD

**Issue by simontegg** [holodex/enspiral-data#5]
Image tasks
- [x] Noshi's logo is on a transparent bakground. Convert to white
- [x] Craftworks, Enspiral services and Freewheeler are all using the same Enspiral logo. Confusing. Change the team ones to initials or name in an image.
- [x] some data are wrong. Phil has Patrik's image, Rose is shown as belonging to Services. Audit and make changes, using Tracey's map of Enspiral Services as the primary source of data.

time estimate: 1 week (29 June)

**Comment by ahdinosaur** [comment]
[Tracey's map of Enspiral Services](https://kumu.io/traceyambrose/enspiral-services#map)
